language: generic  # Use a generic environment for Docker support
services:
  - docker

before_install:
  - docker build -t gevorg1187/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gevorg1187/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: frontend
  env: Frontend-env
  bucket_name: elasticbeanstalk-eu-central-1-686255940580
  bucket_path: frontend
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

